apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.neo4j.neo4j.name }}-lb-neo4j"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Values.neo4j.neo4j.name }}"
  annotations:
    networking.gke.io/load-balancer-type: Internal
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 7474
    targetPort: 7474
    name: http
  - protocol: TCP
    port: 7687
    targetPort: 7687
    name: tcp-bolt
  selector:
    app: "{{ .Values.neo4j.neo4j.name }}"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.neo4j.neo4j.name }}-ext-lb-neo4j"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Values.neo4j.neo4j.name }}"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 7474
    targetPort: 7474
    name: http
  - protocol: TCP
    port: 7687
    targetPort: 7687
    name: tcp-bolt
  selector:
    app: "{{ .Values.neo4j.neo4j.name }}"